// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package userauth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

var isAuthen = false

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"min-h-screen bg-[#0F172A] text-white flex flex-col\"><nav class=\"p-4\"><div class=\"container mx-auto flex justify-between items-center\"><h1 class=\"text-3xl font-bold\">Spectr</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = authButtons().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></nav><div class=\"flex items-center justify-center flex-grow\"><div id=\"main-content\" class=\"w-full max-w-md\"><!-- Content to be replaced will go here --></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func authButtons() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"auth-buttons\"><button hx-get=\"/login\" hx-target=\"#main-content\" class=\"text-gray-400 hover:text-gray-200 py-2 px-4 mr-2 transition duration-300 focus:text-white\">Login</button> <button hx-get=\"/signup\" hx-target=\"#main-content\" class=\"text-gray-400 hover:text-gray-200 py-2 px-4 transition duration-300 focus:text-white\">Sign Up</button></div><div id=\"user-menu\" style=\"display: none;\"><button hx-get=\"/dashboard\" hx-target=\"#main-content\" class=\"text-gray-400 hover:text-gray-200 py-2 px-4 mr-2 transition duration-300 focus:text-white\">Dashboard</button> <button hx-get=\"/profile\" hx-target=\"#main-content\" class=\"text-gray-400 hover:text-gray-200 py-2 px-4 mr-2 transition duration-300 focus:text-white\">Profile</button> <button hx-post=\"/api/logout\" hx-target=\"#main-content\" class=\"text-gray-400 hover:text-gray-200 py-2 px-4 transition duration-300 focus:text-white\">Logout</button></div><script>\n\t\tif (localStorage.getItem('username') && localStorage.getItem('password')) {\n\t\t\tdocument.getElementById('auth-buttons').style.display = 'none';\n\t\t\tdocument.getElementById('user-menu').style.display = 'flex';\n\t\t\tdocument.getElementById('username-display').textContent = localStorage.getItem('username');\n\t\t\t// You can also update the profile image src here if you have it stored\n\t\t} else {\n\t\t\tdocument.getElementById('auth-buttons').style.display = 'flex';\n\t\t\tdocument.getElementById('user-menu').style.display = 'none';\n\t\t}\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
